### PR TITLE
Support for rendering template directly

### PR DESCRIPTION
**Pull request by markwoon**
PR for #23.

### CODE REVIEW

**Comment by baderbuddy** [comment]
This looks great. Have you tried it out and it works as expected? Could you add to the readme an actual example of calling this in your webpack config?

I'll take a closer look probably tomorrow.

**Comment by markwoon** [comment]
Yes, I'm using this now and it's working for me.

I'm added an example of how I'm using it to the README.

**Comment by markwoon** [comment]
@baderbuddy Are there any other changes you'd like me to make on this PR?

**Comment by markwoon** [comment]
Thanks.  Are you planning a release any time soon?

**Comment by baderbuddy** [comment]
Yeah, at some point in the next week (I'm really hoping for tonight).

**Comment by djibarian** [comment]
I’m trying to use the functionality and can’t get the rendered file through the next loader. What I get is a function!

What I’m trying to do is to have a `js` file which has some templates inside. Pass it through this loader and get the result compiled with babel, which is the next loader.

Something I don’t understand is where it says that if another loader is chained `tiny` will be ignored. I think I’m missing something... Could you explain what’s wrong?

The simplified code:

```
{
	test: /file.js$/,
	loader: 'transform-loader',
	options: {
		tiny: true,
		render: { foo: 'bar' }
	},
	{
		test: /file.js$/,
		loader: 'babel-loader'
	}
}
```

**Comment by baderbuddy** [comment]
Djibarian, maybe you should open up a separate issue instead of adding into this one.

I don't quite understand what you're trying to accomplish but the webpack config you've shown doesn't even have mustache-loader listed. The chaining loaders that this issue is talking about is to process the templates further.

**Comment by djibarian** [comment]
Sorry, I edited the question. Where it said `transform-loader` it shoud say `mustache-loader`. I wrote here because I think the problem is related to this functionality. Adding to my question, suppose the `file.js` contents are:

```
export default {
    key: '{{foo}}',
}
```

and I want it to be expanded to 

```
export default {
    key: 'bar',
}
```

before it gets compiled by babel, but that doesn’t work and I don’t understand why because the docs state that if a `render` section is present the templates are rendered and the result is available for further processing. So what I’m missing?

**Pull request merged**
